---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: csi-s3-secret
  namespace: kube-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: csi-s3-secret
    creationPolicy: Owner
  data:
    - secretKey: endpoint
      remoteRef:
        key: S3_ENDPOINT
    - secretKey: accessKeyID
      remoteRef:
        key: S3_ACCESS_KEY_ID
    - secretKey: secretAccessKey
      remoteRef:
        key: S3_ACCESS_KEY_SECRET
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: s3-my-gitops-platform
provisioner: ru.yandex.s3.csi
reclaimPolicy: Retain
parameters:
  mounter: geesefs
  # you can set mount options here, for example limit memory cache size (recommended)
  options: "--memory-limit 1000 --dir-mode 0777 --file-mode 0666"
  # to use an existing bucket, specify it here:
  bucket: my-gitops-platform
  csi.storage.k8s.io/provisioner-secret-name: csi-s3-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/controller-publish-secret-name: csi-s3-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: csi-s3-secret
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: csi-s3-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
