---
# Requires GitLab access token with api scope
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: kube-system
spec:
  provider:
    gitlab:
      auth:
        SecretRef:
          accessToken:
            name: gitlab
            key: token
      projectID: "45439571"
      groupIDs: 
        - "66723933"
