---
kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: natalia-app
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: onechart
      version: "0.47.0"
      sourceRef:
        kind: HelmRepository
        name: onechart
        namespace: kube-system
      interval: 1m
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  targetNamespace: natalia-app
  values:
    ingress:
      ingressClassName: ngrok
      host: natalia-app-retool.ngrok.io
    containerPort: 80
    image:
      repository: docker.io/library/nginx
      tag: latest
