---
kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: nginx
  namespace: kube-system
spec:
  interval: 1m
  targetNamespace: nginx
  chart:
    spec:
      chart: onechart
      version: "0.50.0"
      sourceRef:
        kind: HelmRepository
        name: onechart
        namespace: kube-system
      interval: 1m
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    image:
      repository: docker.io/nginx
      tag: latest
