---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: s3-my-gitops-platform
---
apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: default
spec:
  containers:
   - name: demo
     image: nginx
     volumeMounts:
       - mountPath: /usr/share/nginx/html/s3
         name: webroot
  volumes:
   - name: webroot
     persistentVolumeClaim:
       claimName: demo
       readOnly: false
