---
# Create a HelmRepository object to point to the cnpg chart
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: kube-system
spec:
  interval: 1m
  url: https://cloudnative-pg.github.io/charts
---
# Create a HelmRelease object to install the cnpg
kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: cloudnative-pg
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.18.2"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: kube-system
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values: {}
