---
# Create a HelmRepository object to point to the external-secrets-operator chart
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  interval: 1m
  url: https://charts.external-secrets.io
---
# Create a HelmRelease object to install the external-secrets-operator
kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: external-secrets-operator
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: external-secrets
      version: "0.8.1"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: kube-system
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
