---
# Create a HelmRepository object to point to the k8s-tunnel-controller chart
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: k8s-tunnel-controller
  namespace: kube-system
spec:
  interval: 1m
  url: https://angelbarrera92.github.io/k8s-tunnel-controller
---
# Create a HelmRelease object to install the k8s-tunnel-controller
kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: k8s-tunnel-controller
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: k8s-tunnel-controller
      version: "0.2.0"
      sourceRef:
        kind: HelmRepository
        name: k8s-tunnel-controller
        namespace: kube-system
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    image:
      tag: main
    token:
      existingSecret: k8s-tunnel-controller
      tokenKey: token
