---
# Create a HelmRepository object to point to the kedacore chart
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kedacore
  namespace: kube-system
spec:
  interval: 1m
  url: https://kedacore.github.io/charts
---
# Create a HelmRelease object to install the keda
kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: keda
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: keda
      version: "2.10.2"
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: kube-system
      interval: 1m
  targetNamespace: keda
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
---
# Create a HelmRelease object to install the keda-add-ons-http
kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: keda-add-ons-http
  namespace: kube-system
spec:
  dependsOn:
    - name: keda
  interval: 1m
  chart:
    spec:
      chart: keda-add-ons-http
      version: "0.4.1"
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: kube-system
      interval: 1m
  targetNamespace: keda
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
