---
# Create a HelmRepository object to point to the kyverno chart
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: kube-system
spec:
  interval: 1m
  url: https://kyverno.github.io/kyverno/
---
# Create a HelmRelease object to install the kyverno
kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: kyverno
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: kyverno
      version: "3.0.4"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kube-system
      interval: 1m
  targetNamespace: kyverno
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values: {}
