---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ngrok
  namespace: kube-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: ngrok-secrets
    creationPolicy: Owner
  data:
    - secretKey: NGROK_API_TOKEN
      remoteRef:
        key: NGROK_API_TOKEN
    - secretKey: NGROK_AUTH_TOKEN
      remoteRef:
        key: NGROK_AUTH_TOKEN
---
# Create a HelmRepository object to point to ngrok
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ngrok
  namespace: kube-system
spec:
  interval: 1m
  url: https://ngrok.github.io/kubernetes-ingress-controller
---
# Create a HelmRelease object to install the ngrok-ingress-controller
kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: ngrok-ingress-controller
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: kubernetes-ingress-controller
      version: "0.8.0"
      sourceRef:
        kind: HelmRepository
        name: ngrok
        namespace: kube-system
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
  - kind: Secret
    name: ngrok-secrets
    valuesKey: NGROK_AUTH_TOKEN
    targetPath: credentials.authtoken
  - kind: Secret
    name: ngrok-secrets
    valuesKey: NGROK_API_TOKEN
    targetPath: credentials.apiKey
