---
# Create a HelmRepository object to point to bitnami
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: kube-system
spec:
  interval: 1m
  url: https://charts.bitnami.com/bitnami
---
# Create a HelmRelease object to install the retool
kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: retool-postgresql
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: postgresql
      version: "12.1.15"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: kube-system
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    ssl_enabled: false
    auth:
      database: hammerhead_production
      username: retool
    service:
      port: 5432
    # Use the offical docker image rather than bitnami/docker
    # since Retool depends on the uuid-ossp extension
    image:
      repository: "postgres"
      # 11 is a default, please use 13.4+
      # see https://www.postgresql.org/support/versioning/
      tag: "11"
    postgresqlDataDir: "/data/pgdata"
    primary:
      persistence:
        enabled: true
        mountPath: "/data/"
  valuesFrom:
  - kind: Secret
    name: retool-secrets
    valuesKey: RETOOL_DB_PASSWORD
    targetPath: auth.password
