---
# Create a HelmRepository object to point to the postgres-operator charts
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: postgres-operator
  namespace: kube-system
spec:
  interval: 1m
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
---
# Create a HelmRelease object to install the postgres-operator
kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: postgres-operator
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: postgres-operator
      version: "1.10.0"
      sourceRef:
        kind: HelmRepository
        name: postgres-operator
        namespace: kube-system
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
