---
# Create a HelmRepository object to point to the retool chart
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: retool
  namespace: kube-system
spec:
  interval: 1m
  url: https://charts.retool.com
---
# Create a HelmRelease object to install the retool
kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: retool
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: retool
      version: "5.0.1"
      sourceRef:
        kind: HelmRepository
        name: retool
        namespace: kube-system
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  dependsOn:
    - name: retool-postgresql
      namespace: kube-system
  values:
    replicaCount: 1
    config:
      useInsecureCookies: true
      postgresql: 
        host: retool-postgresql
        db: hammerhead_production
        port: 5432
        user: retool
        passwordSecretName: retool-secrets
        passwordSecretKey: RETOOL_DB_PASSWORD
    image:
      tag: 2.116.6
    ingress:
      enabled: false
    deployment:
      annotations:
        reloader.my-gitops-platform.com/auto: "true"
    env:
      RETOOL_LOAD_FILE_SECRETS: true
      # Use this environment variable to set the Authorization header for the Kubernetes API
      # As %RETOOL_EXPOSED_SERVICEACCOUNT_TOKEN%.
      RETOOL_FILE_EXPOSED_SERVICEACCOUNT_TOKEN: /run/secrets/kubernetes.io/serviceaccount/token
    environmentSecrets:
      - name: RETOOL_EXPOSED_GITHUB_PAT
        secretKeyRef:
          name: retool-secrets
          key: GITHUB_PAT
    resources: {}
    postgresql:
      enabled: false
    extraManifests:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: "{{ include \"retool.serviceAccountName\" . }}"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        name: "{{ include \"retool.serviceAccountName\" . }}"
        namespace: kube-system
  valuesFrom:
    - kind: Secret
      name: retool-secrets
      valuesKey: RETOOL_LICENSE_KEY
      targetPath: config.licenseKey
    - kind: Secret
      name: retool-secrets
      valuesKey: RETOOL_ENCRYPTION_KEY
      targetPath: config.encryptionKey
    - kind: Secret
      name: retool-secrets
      valuesKey: RETOOL_JWT_SECRET
      targetPath: config.jwtSecret
